# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Starter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Starter
pod 'Alamofire', '~> 5.5'
pod 'SDWebImage', '~> 5.0'
pod 'Wormholy', :configurations => ['Debug']
pod 'YouTubePlayer'

end
